[package]
name = "StreamAudioLimiter"
version = "0.2.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
rfd = "0.15.3"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
which = "8.0.0"